### ISSUE TITLE
KVM seems to be broken

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1897]
**Describe the bug**
When using kvm booting stops with
~~~
KVM: KVM_SET_USER_MEMORY_REGION: File exists
~~~

**To Reproduce**
~~~
$ test/test_dos.py --require-attr=cputest PPDOSGITTestCase
Test PP-DOS-GIT  CPU native vm86 + native DPMI (i386 only)                       ... skipped 'native vm86() only on 32bit x86'
Test PP-DOS-GIT  CPU JIT vm86 + native DPMI                                      ... ok (  2.32s)
Test PP-DOS-GIT  CPU JIT vm86 + JIT DPMI                                         ... ok (  1.98s)
Test PP-DOS-GIT  CPU JIT vm86 + KVM DPMI                                         ... FAIL
Test PP-DOS-GIT  CPU KVM vm86 + KVM DPMI                                         ... FAIL
Test PP-DOS-GIT  CPU KVM vm86 + JIT DPMI                                         ... ok (  1.96s)
Test PP-DOS-GIT  CPU KVM vm86 + native DPMI                                      ... ok (  2.25s)
Test PP-DOS-GIT  CPU KVM vm86 + simulated DPMI                                   ... ok (  9.76s)
Test PP-DOS-GIT  CPU simulated vm86 + simulated DPMI                             ... ok ( 10.12s)
Test PP-DOS-GIT  CPU simulated vm86 + KVM DPMI                                   ... FAIL
Test PP-DOS-GIT  CPU simulated vm86 + native DPMI                                ... ok (  2.39s)
Test PP-DOS-GIT  CPU Trap Flag emulated                                          ... FAIL
Test PP-DOS-GIT  CPU Trap Flag KVM                                               ... FAIL

======================================================================
FAIL: Test PP-DOS-GIT  CPU JIT vm86 + KVM DPMI                                        
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_dos.py", line 4778, in test_cpu_jitkvm
    self._test_cpu("emulated", "kvm", 0)
  File "/clients/common/dosemu2.git/test/test_dos.py", line 4759, in _test_cpu
    self.fail("DOS output file not found")
AssertionError: DOS output file not found
Further info in file '/clients/common/dosemu2.git/test_dos.PPDOSGITTestCase.test_cpu_jitkvm.log'
Further info in file '/clients/common/dosemu2.git/test_dos.PPDOSGITTestCase.test_cpu_jitkvm.xpt'

<snip>
~~~

**Attach program/game binaries or provide an URL**
None

**Attach the log**
[t1.zip](https://github.com/dosemu2/dosemu2/files/10687300/t1.zip)

**A regression?**
Yes

**Additional info**
None

**Comment by stsp** [comment]
But all PRs have passed tests!
How is so?
Bart, would you please take a look?

**Comment by andrewbird** [comment]
> But all PRs have passed tests!

Can't test KVM on Github Actions, only Travis has suitable hardware.

**Comment by andrewbird** [comment]
Travis testing also seems to have been disabled - https://app.travis-ci.com/github/dosemu2/dosemu2/builds. For some reason I no longer seem to have access to Dosemu2 team, so can't check the credits etc.

**Comment by stsp** [comment]
https://github.com/orgs/dosemu2/teams/devs
If you mean this, then you are still here.

**Comment by andrewbird** [comment]
> If you mean this, then you are still here.

No, not that. Travis has a dosemu2 team account, just you and I are in it. It's what the credits are allocated to.

**Comment by stsp** [comment]
I haven't changed anything there.
I don't even know where are my
credentials to travis.

**Comment by andrewbird** [comment]
There is no password, it uses Github's Dosemu2 account for authentication. I don't have access to that (but I never have had), so I guess something in the Travis to Github interface must have changed. It's probably not worth the effort to try and fix Travis testing.

**Comment by bartoldeman** [comment]
It seems the first (cpu( tests with kvm pass but then the trap flag one fails at boot.. will check later.

**Comment by bartoldeman** [comment]
hmm I read that wrong on my phone, but that test works for me!

```
$ test/test_dos.py --require-attr=cputest PPDOSGITTestCase
libi86-testsuite-ia16-elf not installed - skipping those

Test PP-DOS-GIT  CPU native vm86 + native DPMI (i386 only)                       ... skipped 'native vm86() only on 32bit x86'
Test PP-DOS-GIT  CPU JIT vm86 + native DPMI                                      ... ok (  0.84s)
Test PP-DOS-GIT  CPU JIT vm86 + JIT DPMI                                         ... ok (  0.78s)
Test PP-DOS-GIT  CPU JIT vm86 + KVM DPMI                                         ... ok (  0.74s)
Test PP-DOS-GIT  CPU KVM vm86 + KVM DPMI                                         ... ok (  0.75s)
Test PP-DOS-GIT  CPU KVM vm86 + JIT DPMI                                         ... ok (  0.78s)
Test PP-DOS-GIT  CPU KVM vm86 + native DPMI                                      ... ok (  0.74s)
Test PP-DOS-GIT  CPU KVM vm86 + simulated DPMI                                   ... ok (  2.15s)
Test PP-DOS-GIT  CPU simulated vm86 + simulated DPMI                             ... ok (  2.12s)
Test PP-DOS-GIT  CPU simulated vm86 + KVM DPMI                                   ... ok (  0.74s)
Test PP-DOS-GIT  CPU simulated vm86 + native DPMI                                ... ok (  0.74s)
Test PP-DOS-GIT  CPU Trap Flag emulated                                          ... ok (  0.75s)
Test PP-DOS-GIT  CPU Trap Flag KVM                                               ... ok (  1.78s)

----------------------------------------------------------------------
Ran 13 tests in 12.909s

OK (skipped=1)
```
I'll check the logs if I can find anything!

**Comment by andrewbird** [comment]
Mmm. I remember there was something odd about how the linux kernel behaved when using KVM with my particular processor in the past. I have 
~~~
ajb@polly:/clients/common/dosemu2.git$ lscpu 
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         36 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
    CPU family:          6
    Model:               15
    Thread(s) per core:  1
    Core(s) per socket:  4
    Socket(s):           1
    Stepping:            11
    CPU max MHz:         2394.0000
    CPU min MHz:         1596.0000
    BogoMIPS:            4800.32
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch
                         _perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm lahf_lm pti tpr_shadow vnmi flexpriority
                          vpid dtherm
Virtualisation features: 
  Virtualisation:        VT-x
Caches (sum of all):     
  L1d:                   128 KiB (4 instances)
  L1i:                   128 KiB (4 instances)
  L2:                    8 MiB (2 instances)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-3
Vulnerabilities:         
  Itlb multihit:         KVM: Mitigation: VMX disabled
  L1tf:                  Mitigation; PTE Inversion; VMX EPT disabled
  Mds:                   Vulnerable: Clear CPU buffers attempted, no microcode; SMT disabled
  Meltdown:              Mitigation; PTI
  Mmio stale data:       Unknown: No mitigations
  Retbleed:              Not affected
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Not affected
  Tsx async abort:       Not affected
~~~

A couple of previous issues with KVM and this processor that affected me were #1306 and #1492, but I don't know if they can offer any clues as to what's going on.

**Comment by bartoldeman** [comment]
@andrewbird 
can you add this little patch and then (ideally!) run with -D+Q
```
diff --git a/src/base/emu-i386/kvm.c b/src/base/emu-i386/kvm.c
index 2c438bd83..6d567c9f8 100644
--- a/src/base/emu-i386/kvm.c
+++ b/src/base/emu-i386/kvm.c
@@ -472,7 +472,11 @@ errcap:
 
 static void set_kvm_memory_region(struct kvm_userspace_memory_region *region)
 {
-  int ret = ioctl(vmfd, KVM_SET_USER_MEMORY_REGION, region);
+  int ret;
+  warn("KVM: map slot=%d flags=%d dosaddr=0x%08llx size=0x%08llx unixaddr=0x%llx\n",
+       region->slot, region->flags, region->guest_phys_addr,
+       region->memory_size, region->userspace_addr);
+  ret = ioctl(vmfd, KVM_SET_USER_MEMORY_REGION, region);
   if (ret == -1) {
     perror("KVM: KVM_SET_USER_MEMORY_REGION");
     leavedos_main(99);
```
that should give me an idea if there's some issue with overlapping KVM regions and what to look for.

**Comment by bartoldeman** [comment]
you should get this kind of output in the log:

```
Warning: KVM: map slot=0 flags=0 dosaddr=0x20110000 size=0x00417000 unixaddr=0x7fce9379a000
Warning: KVM: map slot=1 flags=0 dosaddr=0x00110000 size=0x20000000 unixaddr=0x7fce93cd8000
Warning: KVM: map slot=2 flags=0 dosaddr=0x00000000 size=0x00110000 unixaddr=0x7fce9368a000
```

which reminds me I should really follow the KVM api.txt recommendation to align the unixaddr's at 2MB boundaries. Not only would that potentially allow huge pages, but it would also make debugging easier, as extracting the dosaddr from the unixaddr is much easier then where the latter is still printed.

**Comment by stsp** [comment]
While its not the case here, I wonder
how KVM_BASE should now react to
the simx86 protections. It will probably
bypass them completely now, so some
code should be added to handle that.
Maybe removing `mprotected_kvm` is
too early?

**Comment by andrewbird** [comment]
Here's the logs with the patch applied.
~~~
$ test/test_dos.py PPDOSGITTestCase.test_cpu_jitkvm
Test PP-DOS-GIT  CPU JIT vm86 + KVM DPMI                                         ... FAIL

======================================================================
FAIL: Test PP-DOS-GIT  CPU JIT vm86 + KVM DPMI                                        
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_dos.py", line 4776, in test_cpu_jitkvm
    self._test_cpu("emulated", "kvm", 0)
  File "/clients/common/dosemu2.git/test/test_dos.py", line 4757, in _test_cpu
    self.fail("DOS output file not found")
AssertionError: DOS output file not found
Further info in file '/clients/common/dosemu2.git/test_dos.PPDOSGITTestCase.test_cpu_jitkvm.log'
Further info in file '/clients/common/dosemu2.git/test_dos.PPDOSGITTestCase.test_cpu_jitkvm.xpt'

----------------------------------------------------------------------
Ran 1 test in 1.611s

FAILED (failures=1)
~~~

[t2.zip](https://github.com/dosemu2/dosemu2/files/10696129/t2.zip)

**Comment by stsp** [comment]
Do we know which patch is
offending? If not, Andrew could
you please bisect the last 5-10
patches?

**Comment by bartoldeman** [comment]
It's ok with JIT. What happens is that mprotect_mapping() calls mprotect_kvm() which sets the page tables in the monitor to read-only. Then there is no need to do call mprotect() on the KVM_BASE host mapping any more, though it doesn't hurt. mprotect_kvm() still applies protections to the page tables for a) regions outside dirty logging (ro for JIT), b) for instremu (PROT_NONE), c) to write-protect BIOS areas, and d) for certain DPMI functions.

The issue was always with `mprotected_kvm` was always that the vgaemu code would change protections (both host and page tables) asynchronously in parallel, and for some time the page table would be rw (TLB effects) but the host mapping ro. With dirty logging that is all completely eliminated, and JIT page protections are synchronous, so are not problematic.

**Comment by bartoldeman** [comment]
@andrewbird 
There's no overlap in:
```
Warning: KVM: map slot=0 flags=0 dosaddr=0x20110000 size=0x00417000 unixaddr=0x41889000
Warning: KVM: map slot=1 flags=0 dosaddr=0x00110000 size=0x20000000 unixaddr=0x41f5e000
```
I'll dig a bit further. Perhaps those TSS/identity page ioctls messed things up, since those two matter on some CPUs only IIRC (which would explain why it doesn't happen to me)

**Comment by stsp** [comment]
Thanks for info.
Although it may be interesting for
KVM_BASE to completely ignore
the simx86 protections, and for
example just add protected regions
to the pml machinery for later doing
e_invalidate().

**Comment by andrewbird** [comment]
I bisected to e5ae21af1a6
```git
$ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[e5ae21af1a663418d9e771dff1af8464e81a5528] KVM: map monitor directly after main pool map.
```

**Comment by bartoldeman** [comment]
Thanks, yes, that probably means the monitor needs to be mapped higher up (we could map at it at some arbitrary high fixed place such as 0xf0000000; DOSADDR_REL made it a high place in practise but that's relying on Linux mapping order).

I'll double check first if things are correct in the first place though, or if before that patch a bug was simply hidden.

**Comment by stsp** [comment]
You can use fdpp-buildroot to run dosemu
under core2duo (emulated) CPU. I did that
to debug KVM problems that are not
reproducible otherwise.

**Comment by bartoldeman** [comment]
@andrewbird 
I'm 99% sure this will fix your issue, can you check please?
```
--- a/src/base/emu-i386/kvm.c
+++ b/src/base/emu-i386/kvm.c
@@ -232,6 +232,7 @@ void init_kvm_monitor(dosaddr_t monitor_dosaddr)
   /* trap all I/O instructions with GPF */
   memset(monitor->io_bitmap, 0xff, TSS_IOPB_SIZE+1);
 
+  sregs.tr.base = monitor_dosaddr;
   if (!init_kvm_vcpu()) {
     leavedos(99);
     return;
```
but it'll be cleaner to pass monitor_dosaddr as a parameter to init_kvm_vcpu. I'll do that in a PR.

**Comment by andrewbird** [comment]
Cool, it does
~~~
$ test/test_dos.py --require-attr=cputest PPDOSGITTestCase
Test PP-DOS-GIT  CPU native vm86 + native DPMI (i386 only)                       ... skipped 'native vm86() only on 32bit x86'
Test PP-DOS-GIT  CPU JIT vm86 + native DPMI                                      ... ok (  2.33s)
Test PP-DOS-GIT  CPU JIT vm86 + JIT DPMI                                         ... ok (  2.07s)
Test PP-DOS-GIT  CPU JIT vm86 + KVM DPMI                                         ... ok (  2.09s)
Test PP-DOS-GIT  CPU KVM vm86 + KVM DPMI                                         ... ok (  2.00s)
Test PP-DOS-GIT  CPU KVM vm86 + JIT DPMI                                         ... ok (  2.09s)
Test PP-DOS-GIT  CPU KVM vm86 + native DPMI                                      ... ok (  2.02s)
Test PP-DOS-GIT  CPU KVM vm86 + simulated DPMI                                   ... ok ( 12.21s)
Test PP-DOS-GIT  CPU simulated vm86 + simulated DPMI                             ... ok ( 10.68s)
Test PP-DOS-GIT  CPU simulated vm86 + KVM DPMI                                   ... ok (  2.63s)
Test PP-DOS-GIT  CPU simulated vm86 + native DPMI                                ... ok (  2.25s)
Test PP-DOS-GIT  CPU Trap Flag emulated                                          ... ok (  1.94s)
Test PP-DOS-GIT  CPU Trap Flag KVM                                               ... ok (  3.37s)

----------------------------------------------------------------------
Ran 13 tests in 45.911s

OK (skipped=1)
~~~

**Comment by andrewbird** [comment]
Thanks both!
