### ISSUE TITLE
CPU test failing with KVM / JIT

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1900]
**Describe the bug**
Salient part of the problem seems to be this
~~~
dosemu.bin: kvm.c:487: struct kvm_userspace_memory_region *kvm_get_memory_region(dosaddr_t, dosaddr_t): Assertion `slot < MAXSLOT' failed.
~~~

**To Reproduce**
~~~
$ test/test_dos.py PPDOSGITTestCase.test_cpu_kvmjit
Test PP-DOS-GIT  CPU KVM vm86 + JIT DPMI                                         ... FAIL

======================================================================
FAIL: Test PP-DOS-GIT  CPU KVM vm86 + JIT DPMI                                        
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_dos.py", line 4803, in test_cpu_kvmjit
    self._test_cpu("kvm", "emulated", 0)
  File "/clients/common/dosemu2.git/test/test_dos.py", line 4759, in _test_cpu
    self.fail("DOS output file not found")
AssertionError: DOS output file not found
Further info in file '/clients/common/dosemu2.git/test_dos.PPDOSGITTestCase.test_cpu_kvmjit.log'
Further info in file '/clients/common/dosemu2.git/test_dos.PPDOSGITTestCase.test_cpu_kvmjit.xpt'

----------------------------------------------------------------------
Ran 1 test in 4.168s

FAILED (failures=1)
~~~

**Attach program/game binaries or provide an URL**
None

**Attach the log**
[t1.zip](https://github.com/dosemu2/dosemu2/files/10707000/t1.zip)

**A regression?**
Yes

**Additional info**
No

**Comment by andrewbird** [comment]
I reran the test with +Q logging [t2.zip](https://github.com/dosemu2/dosemu2/files/10707201/t2.zip)

**Comment by stsp** [comment]
Is the problem from the latest PR merge?

**Comment by andrewbird** [comment]
Essentially 99ed8bb4f4d7d is bad, ae1633c7 is good, but I didn't do the bisect (only 2 non merge commits)

**Comment by andrewbird** [comment]
Sorry I made a mistake, ae1633c7d is also bad. I will do a proper bisect.

**Comment by andrewbird** [comment]
5cd6feaef3
~~~
$ git bisect bad
5cd6feaef39dcf95767c49a976cb967236effd58 is the first bad commit
commit 5cd6feaef39dcf95767c49a976cb967236effd58
Author: Bart Oldeman <bartoldeman@users.noreply.github.com>
Date:   Mon Feb 6 21:15:36 2023 -0500

    KVM: use dirty logging for VGA buffers.
~~~

**Comment by andrewbird** [comment]
So is this another one of those issues that is only broken for me, or can anyone reproduce?

**Comment by stsp** [comment]
For me KVM works.
But previous example shown that
the problems are not always
cpu-specific. I have no idea why
it broke only for you, if the monitor
address was evaluated from an
uninitialized var...

**Comment by stsp** [comment]
Oh, what, no, it doesn't work if
dpmi is set to cpu-emu!

**Comment by andrewbird** [comment]
Ahh, that's good then, thanks.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by andrewbird** [comment]
Cool, works for me, thanks!
