### ISSUE TITLE
XMS test failing (with KVM)

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1940]
**Describe the bug**
XMS test fails (okay under CI)

**To Reproduce**
~~~
$ test/test_dos.py PPDOSGITTestCase.test_memory_xms
Test PP-DOS-GIT  Memory XMS                                                      ... FAIL

======================================================================
FAIL: Test PP-DOS-GIT  Memory XMS                                                     
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_dos.py", line 3302, in test_memory_xms
    memory_xms(self)
  File "/clients/common/dosemu2.git/test/func_memory_xms.py", line 214, in memory_xms
    self.assertIn("Test 1 OK", results)
AssertionError: 'Test 1 OK' not found in 

C:\>testit.bat
testit.bat

C:\>c:\xmstest
XMS present
XMS at 97:1a6
XMS alloc ok
XMS move ok
XMS map ok
DPMI map ok, addr=0x1ea20000
DPMI wrap-around ok, ptr=1c8ae000, base=02172000
Exiting due to signal SIGSEGV
Page fault at eip=0000542a, error=0004
eax=000954f4 ebx=00001973 ecx=000954f8 edx=1c8ae023 esi=ffffffff edi=1c8ae023
ebp=00092c38 esp=00092c38 program=C:\XMSTEST.EXE
cs: sel=0157  base=02172000  limit=ffffffff
ds: sel=015f  base=02172000  limit=ffffffff
es: sel=0097  invalid
fs: sel=0137  base=00000c40  limit=0000ffff
gs: sel=016f  base=00000000  limit=0010ffff
ss: sel=015f  base=02172000  limit=ffffffff
App stack: [00096600..00016600]  Exceptn stack: [000165ac..0001466c]

Call frame traceback EIPs:
  0x0000542a
  0x00008a81
  0x000045b9
  0x00001d3a
  0x0000580d
~~~

**Attach program/game binaries or provide an URL**
N/A

**Attach the log**
[t1.zip](https://github.com/dosemu2/dosemu2/files/10912835/t1.zip)

**A regression?**
Yes

**Additional info**
N/A

**Comment by andrewbird** [comment]
Thanks @bartoldeman , be20f2d33595 fixed it for me!

**Comment by bartoldeman** [comment]
ah we saw this in parallel, sorry I missed this, or I would have closed this with the PR!
