### ISSUE TITLE
FPU - Qemu tests (SIM) rounding error

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#2060]
**Describe the bug**
Using the Qemu FPU tests integrated in my ci-12 PR #1885 we can see that with SIM the results are slightly different to that expected seemingly due to rounding.

**To Reproduce**
1/ Use the branch referenced by ci-12 PR
2/ `make -C test/fpu clean all`
3/ Run `test/test_dos.py PPDOSGITTestCase.test_fpu_qemu_f2xm1_SIM_SIM`

**Attach program/game binaries or provide an URL**
.

**Attach the log**
[t1.zip](https://github.com/dosemu2/dosemu2/files/12188533/t1.zip)

**A regression?**
Not sure, but I think it's unlikely to be so.

**Additional info**
.

**Comment by stsp** [comment]
```
$ test/test_dos.py PPDOSGITTestCase.test_fpu_qemu_f2xm1_SIM_SIM
Test PP-DOS-GIT  FPU (Qemu)           f2xm1     SIM_SIM                          ... ERROR

======================================================================
ERROR: Test PP-DOS-GIT  FPU (Qemu)           f2xm1     SIM_SIM                         
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stas/src/dosemu2/test/fpu/qemu.py", line 42, in do_test_qemu
    qemu_test_item(self, test, x, y, z)
  File "/home/stas/src/dosemu2/test/fpu/qemu.py", line 68, in qemu_test_item
    copy(efil.with_suffix('.exe'), self.workdir / "fputest.exe")
  File "/usr/lib/python3.11/shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/stas/src/dosemu2/test/fpu/test-i386-f2xm1.exe'

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
```

**Comment by andrewbird** [comment]
Sorry, I forgot to say you need to do `make -C test/fpu clean all` in the build directory first.

**Comment by stsp** [comment]
Would you like to add some makefile
targets, so that instead of running test_dos.py
directly with broken deps, I'd run it via make,
getting the deps built as needed?

**Comment by stsp** [comment]
There are obviously the failures in the
test-case itself:
```
FAIL: f2xm1 0xb.3cae6b3899e20cep-5, expected 0x8.d1949341f4b6bafp-5 or
0x8.d1949341f4b6bbp-5, got 0x8.d1949341f4b6bb1p-5\r\n
```

Note that the last 2 digits do match:
`0x8.d1949341f4b6bbp-5` matches `0x8.d1949341f4b6bb1p-5`.
So the "got" answer is just a more precise
variation of what was expected.

**Comment by stsp** [comment]
Instead of the literal comparison, you just
need to subtract reply from expected answer,
take absolute value and make sure it doesn't
exceed the threshold.

**Comment by stsp** [comment]
Maybe you can keep the literal comparisons
for native cpu backends (like kvm) where
the exact match is guaranteed by testing
the physical CPU and using the physical
CPU for getting the expected values.
But I suppose even the physical CPUs may
alter the rounding algorithms eventually.

**Comment by stsp** [comment]
Or you can try just avoid the last
digit by the use of the different output
formatter.
